[RPD-3222] Search with csv
sungyeopTW/toy-weather-ios pull request #9
Opened 2022-05-25 06:15 UTC by sungyeopTW

# pull request: :hatching_chick: feature

## :mag_right: 작업 내용 (Content)
[RPD-3222] [Toy] csv 파일 연결
1. 기능추가 사항
    - csv파일 추가
    - 검색기능에 csv파일 연결 (`LocationSearchTable`)
    - 즐겨찾기 기능 (전체)

2. 수정 사항
    - 전체적인 fontSize 수정
    - 날씨 상세정보 UI 수정 (`WeatherDetailViewController`)
    - View에서 initialize될 부분과 지속적으로 바뀌는 부분의 method 분리

4. 리팩토링 사항
    - 내부에서만 사용되는 변수/상수 와 함수들 private 붙임
    - closure 문법 사용중 생략가능 부분 생략 안된 사항 생략
    - if문을 switch문으로 수정해 가독성 높이고 에러확인을 위한 `fatalError` 추가
    - 연산프로퍼티 사용 가능한 부분 연산프로퍼티로 수정 (`RootViewController` -> `numberOfRowsInSection` -> `cellCount`)
    - 중복로직 함수로 분리 (`WeatherDetailCollectionViewCell` -> `setupLabelText`)

<br>

2022-05-25 09:42 UTC, nexmondTW requested changes
![스크린샷 2022-05-25 오후 6 41 18](https://user-images.githubusercontent.com/27802353/170232767-0ff55842-28cc-443e-a420-c658266da344.png)
 LocationSource.csv의 절대경로를 확인해주세요. 파일이 누락되어 빌드에 실패합니다.

2022-05-25 09:48 UTC, nexmondTW commented
toy-weather-ios/Resources/LocationSource.csv 로 경로를 수정하여 빌드를 시도했으나,
`Fatal error: Index out of range` 오류로 예외가 발생합니다.

![스크린샷 2022-05-25 오후 6 46 41](https://user-images.githubusercontent.com/27802353/170233866-d9e9fc5c-b606-4d94-afee-7d36490b26e5.png)
아이디 열이 없는 파일이어서 인 듯 합니다.

2022-05-25 10:10 UTC, sungyeopTW commented
@nexmondTW
세상에..
프로젝트 내부의 csv파일은 id가 없는 이전 파일 그대로인 상황에서
제 mac의 local에 id가 있는 새로운 파일을 만들고
프로젝트에서는 그 파일의 path를 잡아놓았었습니다ㅜㅜㅜ

수정했습니다!

2022-05-26 02:35 UTC, nexmondTW reviewed
City 유형을 String 배열보다는, 구조체로 정의하는 것은 어떨까요?
City는 결국 String 배열이기 때문에, extension에 정의된 계산변수는 모든 곳에서 사용될 수 있습니다.
ex) `keys.location == keys[1]`

2022-05-26 05:00 UTC, sungyeopTW commented
@nexmondTW
말씀하신대로 City를 struct로 바꾸어보았습니당!!

2022-05-27 02:10 UTC, sungyeopTW commented
@nexmondTW 
구두로 피드백 받았던 부분에 대해 추가 리팩토링 진행했습니다!
1. `City` 를 struct로 변경하고 Equatable 적용
2. `WeatherDetailViewController`에 `init` lifeCycle 추가
3.  섭씨/화씨 관련부분 `Temperature` struct로 변경
4. `delegate` 구조 변경 및 delegate와 내부 method에 대한 Naming 변경

2022-05-27 05:38 UTC, nexmondTW commented on toy-weather-ios/Protocols/ButtonInteractionDelegate.swift
> +    func didTabBookmarkButtonOnCell(_ isBookmarked: Bool, on cellData: City)
두 메서드, `didTabBookmarkButton`와 `didTabBookmarkButtonOnCell`를 하나로 통합해보시는 건 어떨까요?

2022-05-27 05:39 UTC, nexmondTW approved these changes

2022-05-27 06:09 UTC, sungyeopTW commented on toy-weather-ios/Protocols/ButtonInteractionDelegate.swift
> +    func didTabBookmarkButtonOnCell(_ isBookmarked: Bool, on cellData: City)
@nexmondTW 수정완료 ☕️

`didTabBookmarkButtonOnCell` 을 없애고
`didTabBookmarkButton` 에 `on CellData: City?` 로 옵셔널처리를 해보았습니당!!

근데 왜 연차 안즐기십니까.......

2022-05-30 06:40 UTC, nexmondTW commented
LGTM

2022-05-30 06:40 UTC, merged